name: Verificar archivo HTML

on:
  push:
    branches: [main]

jobs:
  check-html:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Verificar si index.html existe
        run: |
          if [ -f "index.html" ]; then
            echo "✅ index.html existe"
          else
            echo "❌ index.html NO existe"
            exit 1
          fi
